### ISSUE TITLE
Infinite funds are never available

### ISSUE THREAD

**Issue by dimitri-xyz** [gnosis/dex-research#10]
When specifying buy or sell orders as described here:
https://github.com/gnosis/dex-research/blob/13e8ebac59fbc14a29de3ec5dd893b68991bb807/BatchAuctionOptimization/batchauctions.tex#L213

There will always exist an implicit (finite) limit on the funds available to perform the transaction. The $ +\infty $ is "kinda fake" as it will be substituted by the minimum of how much the person placing the order has in reserves and how much she is willing to spend. However, the \infty is necessary because it is being used to mark the order as either a buy (bid) or a sell (ask) order.

All orders will swap token i for token j. I would suggest having only 1 type of order (either buy or sell) and swapping the tokens instead. Here's a suggestion:

1. (j,k,\overline{x},\pi) is an order to buy a maximum of \overline{x} tokens j making payments in token k for a price of at most \pi.
2. (k,j,\overline{y},\rho) has exactly the same interpretation (note the swapped order of j and k), is an order to buy a maximum of \overline{y} tokens k making payments in token j for a price at most \rho.

The second "buy" order is equivalent to a "sell" order for token j.

(Notice that the limit order types described in the paper do *not* span all limit order types possible. It is not possible to say: buy as many as possible for a maximum cost \overline{c} and pay at most \pi per token.)

Hope this helps!

**Comment by bh2smith** [comment]
Hey this is a pretty great suggestion. We have made similar changes in other internal documentation. However, for this particular article @tomtiger87 should have a look first (at least).

**Comment by tomtiger87** [comment]
Indeed - I have removed buy orders from the models (since they are treated similar to sell orders from a modelling/computational perspective and only add notational complexity).

@dimitri-xyz : Not sure if I understand the following correctly:

> (Notice that the limit order types described in the paper do not span all limit order types possible. It is not possible to say: buy as many as possible for a maximum cost \overline{c} and pay at most \pi per token.)

Isn't this just a regular limit sell order (in which you'd be happy to receive as many buy-tokens as possible)? If not, could you please provide an example to show the difference?

Thanks!

**Comment by dimitri-xyz** [comment]
@tomtiger87 ,

I guess I did this commenting on other issue (https://github.com/gnosis/dex-research/issues/9#issuecomment-456379271).

If I operate on the BTC-USD market and I have 4000 USD on my account, I can usually place an order to buy 2 BTC for 2000 USD/BTC each as I have enough funds to cover that. But I usually will *not* be allowed to place an order to buy 3 BTC for that same price of $2000 as I would not have enough funds to cover the cost *if all BTC were sold at the maximum $2000 price* (as 3 x 2000 = $6000 rather than $4000). But it may be that there are 2 BTCs being sold for $1000 each and one for $2000. So, excluding this kind of order is not necessarily good for the trader (as it limits the kind of preferences they can express), it is just a way to make the market mechanism simpler.

There is nothing wrong with an order to Buy 3 BTC paying at most $2000 per BTC and spending a total of at most $4000, but this complicates your orderbook. If this order doesn't get completely executed, you will need to add a "cost" column to the orderbook. So, usually orders specifying costs are only allowed as market orders.
